fh=open("employee3.dat","r")
#print("current position",fh.seek(30))
print("current position",fh.seek(-17,2))
#print(fh.read(2))
#print("current position",fh.tell())
#print(fh.read(5))
#print("current position",fh.tell())
#print(fh.read(8))
print("current position",fh.tell())
