player1 = str(input("Enter the player's name: "))
player2 = str(input("Enter the player's name: "))
player3 = str(input("Enter the player's name: "))
player4 = str(input("Enter the player's name: "))
player5 = str(input("Enter the player's name: "))
player6 = str(input("Enter the player's name: "))
score1 = int(input("Enter the player's score: "))
score2 = int(input("Enter the player's score: "))
score3 = int(input("Enter the player's score: "))
score4 = int(input("Enter the player's score: "))
score5 = int(input("Enter the player's score: "))
score6 = int(input("Enter the player's score: "))

a = {player1:score1, player2:score2, player3:score3, player4:score4, player5:score5, player6:score6}
print(a)
